name: Build LaTeX document
on:
  push:
    paths:
      - cv-data-engineer/**
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: cv-data-engineer
          root_file: cv.tex
          latexmk_use_xelatex: true
          post_compile: "latexmk -c"
          extra_fonts: |
            ./fonts/Ubuntu-B.ttf
            ./fonts/Ubuntu-BI.ttf
            ./fonts/Ubuntu-C.ttf
            ./fonts/Ubuntu-L.ttf
            ./fonts/Ubuntu-LI.ttf
            ./fonts/Ubuntu-M.ttf
            ./fonts/Ubuntu-MI.ttf
            ./fonts/UbuntuMono-B.ttf
            ./fonts/UbuntuMono-BI.ttf
            ./fonts/UbuntuMono-R.ttf
            ./fonts/UbuntuMono-RI.ttf
            ./fonts/Ubuntu-R.ttf
            ./fonts/Ubuntu-RI.ttf
            ./fonts/Ubuntu-Th.ttf
      - name: Upload PDF to workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: cv-data-engineer
          path: cv-data-engineer/cv.pdf
